### ISSUE TITLE
Suggestion - Tool module, have owner be member

### ISSUE THREAD

**Issue by chris18890** [FlinchyMcFlincherson/TVCOG_Seltzer#38]
In the tool module  one of the fields is 'owner', which is currently just a string, this could be set to be a member

Also, the 'createdBy' field doesn't seem to be used at the moment, you could also have this be the currently logged on user

Another thing - the forms don't need the be a float class.

Can I just ask why you merged the "command_tool_add" & "tool_save" functions?

**Comment by FlinchyMcFlincherson** [comment]
Re: The "owner" field - Agree.  I actually just stumbled on the functionality that creates the arrays used to automatically populated drop-downs used elsewhere, so I haven't had a chance to figure it out completely.  This is definitely something that's called for in a couple of places in the system, though.

Re: The "createdBy" field - I haven't figured out how to identify the currently logged in user yet.  I was hoping there was already an obvious function somewhere that just returned the currently logged in user as a string, but I've been able to find anything like that.  If I could do that here, I could implement it elsewhere, as it's always kind of bugged me that all the database tables lack "created by", "created on", etc. fields. (see issue #32 and issue #33).

Re: float class forms - This is the result of my ignorance of stylesheets.  The forms I was emulating were float class, so I carried that design over, that's all.  Learning the finer points of CSS has been lower on the priority list than getting some form of functionality out there to use.

Re: The "command_tool_add" & "tool_save" functions - This module was actually based on the functions that create and maintain membership plans, and since both functions existed for that process, I ended up replicating both in the Tool module as well.  Honestly, I couldn't see a huge difference between the two at the time, so later, once I had everything working, I eliminated one for efficiency's sake.  I defer to your knowledge on the subject though, can you tell me why having both is necessary?

**Comment by chris18890** [comment]
Re the owner field - there's an auto complete function that does this, I'll try to write something up for it over the weekend for you.

There is a function already, it's a bit convoluted but I think it's somehting along the lines of userID(), not sure if it's that simple as just setting $createdby = userID;

fair enough, I'll tidy this up & put in a pull request

Ah, ok, I though it'd been based off the key module!  I've just re-written the member module, which manages the plans & memberships, so if you take a look at https://github.com/chris18890/seltzer/tree/issue281 you can see how I did it.

The reason behind it is to separate the user interaction & the SQL work, in that the command_module_object_function(); deals with checking user permissions & returning the user to the proper location, it just takes the input from the form & passes it on to module_object_save(); (or whatever it's called) which does the actual SQL work - an advantage of this is that the module_object_save(); is easier to call from another function, such as how the main function for adding a member actually starts by saving a contact object, then creates the user object, then the member object (including membership(s)).

While I think you've been doing some brilliant work, as I mentioned before & as @elplatt said on the dev list (https://groups.google.com/forum/#!topic/seltzercrm-dev/sOTWXMNtdsM) a fair amount of things on the original repo have changed since you forked it, so you might want to consider updating your fork.  If you use email/skype/google hangout I'm happy to help you do this :)
